### ISSUE TITLE
Orange release breaks ewoksdemo

### ISSUE THREAD

**Issue by poautran** [ewoks-kit/ewoksorange#32]
***In GitLab by @woutdenolf on Dec 15, 2023, 13:51 GMT+1:***

```
(ewokstest) denolf@lindenolf:~$ ewoks-canvas
/home/denolf/ewokstest/lib/python3.8/site-packages/silx/io/h5py_utils.py:50: H5pyDeprecationWarning: h5py.get_config().swmr_min_hdf5_version is deprecated. This version of h5py does not support older HDF5 without SWMR.
  HDF5_SWMR_VERSION = calc_hexversion(*h5py.get_config().swmr_min_hdf5_version[:3])
2023-12-15 13:45:42,261:ERROR:orangecanvas.registry.discovery: An exception occurred while processing EntryPoint.parse('Ewoks Demo = orangecontrib.ewoksdemo').
Traceback (most recent call last):
  File "/home/denolf/ewokstest/lib/python3.8/site-packages/orangecanvas/registry/discovery.py", line 141, in run
    self.process_category_package(
  File "/home/denolf/ewokstest/lib/python3.8/site-packages/orangecanvas/registry/discovery.py", line 213, in process_category_package
    cat_desc.project_name = distribution.name
  File "/home/denolf/ewokstest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2900, in __getattr__
    return getattr(self._provider, attr)
AttributeError: 'PathMetadata' object has no attribute 'name'
```

Caused by new release

https://pypi.org/project/orange-canvas-core/#history

https://pypi.org/project/orange-widget-base/#history

This fixes the problem

```
pip install orange-canvas-core==0.1.35 orange-widget-base==4.22.0
```

*Migrated from GitLab: https://gitlab.esrf.fr/workflow/ewoks/ewoksorange/-/issues/32*

**Comment by abmajith** [comment]
this appears again,

pip show ewoksorange
Name: ewoksorange
Version: 6.0.0rc7


```
woks-canvas
2026-09-18 09:24:36,309:ERROR:orangecanvas.application.examples: Could not load examples from <importlib.metadata.PathDistribution object at 0x784ad745fac0>
Traceback (most recent call last):
  File "/home/noordhee/BMLine_Projects/ewoksImageD11/ewoks3dxrd/venv/lib/python3.13/site-packages/orangecanvas/application/examples.py", line 50, in workflows
    examples = ep.load()
  File "/home/noordhee/miniforge3/lib/python3.13/importlib/metadata/__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "/home/noordhee/miniforge3/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1395, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/noordhee/BMLine_Projects/ewoksImageD11/ewoks3dxrd/venv/lib/python3.13/site-packages/orangecontrib/ewoksdemo/tutorials/__init__.py", line 6, in <module>
    raise RuntimeError("ewoksdemo is disabled")
RuntimeError: ewoksdemo is disabled
```
